# Generated by Django 5.2.14 on 2026-05-11 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'السنة الأولى'), (2, 'السنة الثانية'), (3, 'السنة الثالثة'), (4, 'السنة الرابعة')], null=True, verbose_name='السنة الدراسية')),
                ('semester', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'الفصل الأول'), (2, 'الفصل الثاني')], null=True, verbose_name='الفصل الدراسي')),
                ('icon', models.CharField(choices=[('school', 'مدرسة'), ('radiology', 'الأشعات'), ('body_system', 'الجسم'), ('biotech', 'التكنولوجيا الحيوية'), ('microbiology', 'الميكروبيولوجي'), ('clinical_notes', 'الملاحظات الإكلينيكية'), ('medical_services', 'الخدمات الطبية'), ('psychology', 'علم النفس'), ('skeleton', 'الهيكل العظمي'), ('lab_panel', 'لوحة المختبر'), ('science', 'العلوم'), ('health_and_safety', 'الصحة والسلامة'), ('medication', 'الأدوية'), ('vaccines', 'اللقاحات'), ('monitor_heart', 'مراقبة القلب'), ('ecg_heart', 'تخطيط القلب'), ('bloodtype', 'فصائل الدم'), ('healing', 'العلاج'), ('emergency', 'الطوارئ'), ('local_hospital', 'المستشفى'), ('stethoscope', 'السماعة الطبية'), ('heart_broken', 'أمراض القلب'), ('neurology', 'الأعصاب'), ('pulmonology', 'الجهاز التنفسي'), ('ophthalmology', 'طب العيون'), ('dentistry', 'طب الأسنان'), ('pediatrics', 'طب الأطفال'), ('elderly', 'طب الشيخوخة'), ('pregnant_woman', 'النساء والولادة'), ('female', 'صحة المرأة'), ('male', 'صحة الرجل'), ('accessible', 'العلاج الطبيعي'), ('fitness_center', 'اللياقة والتأهيل'), ('monitor_weight', 'الوزن والتغذية'), ('nutrition', 'التغذية'), ('coronavirus', 'الأمراض المعدية'), ('sanitizer', 'التعقيم'), ('masks', 'الوقاية'), ('experiment', 'التجارب'), ('genetics', 'الوراثة'), ('vaccines', 'التطعيم'), ('syringe', 'الحقن'), ('pill', 'الحبوب الطبية'), ('medical_information', 'المعلومات الطبية'), ('patient_list', 'المرضى'), ('ambulance', 'الإسعاف'), ('lab_research', 'الأبحاث المخبرية'), ('orthopedics', 'العظام'), ('dermatology', 'الجلدية'), ('urology', 'المسالك البولية'), ('psychiatry', 'الطب النفسي'), ('medical_mask', 'الكمامات'), ('wheelchair_pickup', 'الكراسي المتحركة'), ('hearing', 'السمع'), ('visibility', 'البصر'), ('handshake', 'الرعاية الصحية'), ('self_improvement', 'الصحة النفسية'), ('quiz', 'الاختبارات'), ('assignment', 'الواجبات'), ('link', 'الروابط'), ('menu_book', 'المراجع'), ('video_library', 'الفيديوهات'), ('article', 'المقالات'), ('description', 'الملفات'), ('folder', 'المجلدات'), ('image', 'الصور'), ('smart_display', 'العروض'), ('record_voice_over', 'المحاضرات'), ('live_help', 'الأسئلة الشائعة'), ('forum', 'النقاشات'), ('chat', 'الدردشة'), ('groups', 'المجموعات'), ('person', 'الطلاب'), ('supervisor_account', 'المشرفين'), ('notifications', 'الإشعارات'), ('event', 'الأحداث'), ('calendar_month', 'التقويم'), ('timeline', 'التقدم'), ('insights', 'الإحصائيات'), ('analytics', 'التحليلات'), ('dashboard', 'لوحة التحكم'), ('settings', 'الإعدادات'), ('admin_panel_settings', 'الإدارة'), ('search', 'البحث'), ('bookmark', 'المحفوظات'), ('favorite', 'المفضلة'), ('download', 'التحميلات'), ('upload', 'الرفع'), ('cloud', 'السحابة'), ('security', 'الأمان'), ('lock', 'الخصوصية'), ('support', 'الدعم'), ('email', 'البريد'), ('language', 'المواقع'), ('public', 'الإنترنت')], default='school', max_length=50, verbose_name='الأيقونة')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='رمز المقرر')),
                ('name', models.CharField(max_length=120, verbose_name='اسم المقرر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'المقرر',
                'verbose_name_plural': 'المقررات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='التميز الأكاديمي', max_length=100, verbose_name='نص الوسم')),
                ('hero_title', models.CharField(max_length=255, verbose_name='عنوان الواجهة الرئيسية')),
                ('hero_description', models.TextField(verbose_name='وصف الواجهة الرئيسية')),
                ('primary_button_text', models.CharField(default='استكشف المصادر', max_length=80, verbose_name='نص الزر ')),
                ('primary_button_url', models.CharField(default='#', max_length=255, verbose_name='رابط الزر')),
                ('hero_background_image_url', models.URLField(blank=True, verbose_name='رابط صورة الخلفية')),
                ('show_specializations', models.BooleanField(default=True, verbose_name='إظهار التخصصات في الرئيسية')),
                ('show_team', models.BooleanField(default=False, verbose_name='إظهار فريق العمل في الرئيسية')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'محتوى الصفحة الرئيسية',
                'verbose_name_plural': 'محتوى الصفحة الرئيسية',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='كلية العلوم الطبية التطبيقية', max_length=180, verbose_name='اسم الموقع')),
                ('site_tagline', models.CharField(blank=True, max_length=220, verbose_name='الوصف المختصر')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('primary_logo_url', models.URLField(blank=True, verbose_name='رابط الشعار الأساسي')),
                ('secondary_logo_url', models.URLField(blank=True, verbose_name='رابط الشعار الثانوي')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط المختصر')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='رابط الصورة')),
                ('icon', models.CharField(choices=[('school', 'مدرسة'), ('radiology', 'الأشعات'), ('body_system', 'الجسم'), ('biotech', 'التكنولوجيا الحيوية'), ('microbiology', 'الميكروبيولوجي'), ('clinical_notes', 'الملاحظات الإكلينيكية'), ('medical_services', 'الخدمات الطبية'), ('psychology', 'علم النفس'), ('skeleton', 'الهيكل العظمي'), ('lab_panel', 'لوحة المختبر'), ('science', 'العلوم'), ('health_and_safety', 'الصحة والسلامة'), ('medication', 'الأدوية'), ('vaccines', 'اللقاحات'), ('monitor_heart', 'مراقبة القلب'), ('ecg_heart', 'تخطيط القلب'), ('bloodtype', 'فصائل الدم'), ('healing', 'العلاج'), ('emergency', 'الطوارئ'), ('local_hospital', 'المستشفى'), ('stethoscope', 'السماعة الطبية'), ('heart_broken', 'أمراض القلب'), ('neurology', 'الأعصاب'), ('pulmonology', 'الجهاز التنفسي'), ('ophthalmology', 'طب العيون'), ('dentistry', 'طب الأسنان'), ('pediatrics', 'طب الأطفال'), ('elderly', 'طب الشيخوخة'), ('pregnant_woman', 'النساء والولادة'), ('female', 'صحة المرأة'), ('male', 'صحة الرجل'), ('accessible', 'العلاج الطبيعي'), ('fitness_center', 'اللياقة والتأهيل'), ('monitor_weight', 'الوزن والتغذية'), ('nutrition', 'التغذية'), ('coronavirus', 'الأمراض المعدية'), ('sanitizer', 'التعقيم'), ('masks', 'الوقاية'), ('experiment', 'التجارب'), ('genetics', 'الوراثة'), ('vaccines', 'التطعيم'), ('syringe', 'الحقن'), ('pill', 'الحبوب الطبية'), ('medical_information', 'المعلومات الطبية'), ('patient_list', 'المرضى'), ('ambulance', 'الإسعاف'), ('lab_research', 'الأبحاث المخبرية'), ('orthopedics', 'العظام'), ('dermatology', 'الجلدية'), ('urology', 'المسالك البولية'), ('psychiatry', 'الطب النفسي'), ('medical_mask', 'الكمامات'), ('wheelchair_pickup', 'الكراسي المتحركة'), ('hearing', 'السمع'), ('visibility', 'البصر'), ('handshake', 'الرعاية الصحية'), ('self_improvement', 'الصحة النفسية'), ('quiz', 'الاختبارات'), ('assignment', 'الواجبات'), ('link', 'الروابط'), ('menu_book', 'المراجع'), ('video_library', 'الفيديوهات'), ('article', 'المقالات'), ('description', 'الملفات'), ('folder', 'المجلدات'), ('image', 'الصور'), ('smart_display', 'العروض'), ('record_voice_over', 'المحاضرات'), ('live_help', 'الأسئلة الشائعة'), ('forum', 'النقاشات'), ('chat', 'الدردشة'), ('groups', 'المجموعات'), ('person', 'الطلاب'), ('supervisor_account', 'المشرفين'), ('notifications', 'الإشعارات'), ('event', 'الأحداث'), ('calendar_month', 'التقويم'), ('timeline', 'التقدم'), ('insights', 'الإحصائيات'), ('analytics', 'التحليلات'), ('dashboard', 'لوحة التحكم'), ('settings', 'الإعدادات'), ('admin_panel_settings', 'الإدارة'), ('search', 'البحث'), ('bookmark', 'المحفوظات'), ('favorite', 'المفضلة'), ('download', 'التحميلات'), ('upload', 'الرفع'), ('cloud', 'السحابة'), ('security', 'الأمان'), ('lock', 'الخصوصية'), ('support', 'الدعم'), ('email', 'البريد'), ('language', 'المواقع'), ('public', 'الإنترنت')], default='school', max_length=50, verbose_name='الأيقونة')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'التخصصات',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('job_title', models.CharField(max_length=180, verbose_name='المسمى الوظيفي')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة')),
                ('image_url', models.URLField(blank=True, verbose_name='رابط الصورة')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عضو فريق',
                'verbose_name_plural': 'فريق العمل',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='العنوان')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('slides', 'سلايدات'), ('lecture', 'محاضرة'), ('video', 'فيديو'), ('summary', 'ملخص'), ('exam', 'اختبار'), ('link', 'رابط')], max_length=20, verbose_name='نوع المورد')),
                ('url', models.URLField(blank=True, verbose_name='الرابط')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='app.course', verbose_name='المقرر')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموارد',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='courses', to='app.specialization', verbose_name='التخصصات'),
        ),
    ]
