# Generated by Django 5.2.14 on 2026-05-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='primary_logo_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='secondary_logo_url',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='primary_logo_url',
            field=models.URLField(blank=True, verbose_name='رابط الشعار الأساسي'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='secondary_logo_url',
            field=models.URLField(blank=True, verbose_name='رابط الشعار الثانوي'),
        ),
    ]
