# Generated by Django 5.2.14 on 2026-05-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_sitesettings_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='show_specializations',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='show_team',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_specializations',
            field=models.BooleanField(default=True, verbose_name='إظهار التخصصات في الرئيسية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_team',
            field=models.BooleanField(default=True, verbose_name='إظهار فريق العمل في الرئيسية'),
        ),
    ]
