# Generated by Django 5.2.14 on 2026-05-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_homepagecontent_show_specializations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_description',
            field=models.TextField(default='اكتشف مجموعة شاملة من الموارد الدراسية المصممة خصيصًا لطلاب كلية العلوم الطبية التطبيقية. من المقررات الدراسية إلى الاختبارات والمحاضرات، كل ما تحتاجه لتحقيق التفوق الأكاديمي في مكان واحد.', verbose_name='وصف الواجهة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_title',
            field=models.CharField(default='مصادر دراسية لطلاب كلية العلوم الطبية التطبيقية', max_length=255, verbose_name='عنوان الواجهة الرئيسية'),
        ),
    ]
